#ifndef VOCAB_H
#define VOCAB_H

// AUTO-GENERATED FILE - DO NOT EDIT BY HAND.
// Source of truth: resources/vocab_db.json
// Regenerate with: python3 tools/generate_vocab.py

typedef struct {
  const char *term;
  const char *meaning;
  const char *example;
  const char *etymology;
  const char *phonetic;
  int difficulty;  // 1=basic, 2=intermediate, 3=advanced
  const char *category;
} VocabEntry;

static const VocabEntry vocab_list[] = {
  {"Eloquent", "Fluent and persuasive in speaking", "The speaker was eloquent and captivating.", "Latin: eloquens", "EL-uh-kwunt", 2, "General"},
  {"Ephemeral", "Lasting for a very short time", "The beauty of cherry blossoms is ephemeral.", "Greek: ephemeros", "uh-FEM-er-ul", 3, "General"},
  {"Ubiquitous", "Present everywhere at once", "Smartphones are ubiquitous in modern society.", "Latin: ubique", "yoo-BIK-wi-tus", 3, "General"},
  {"Serendipity", "Finding good things by chance", "Meeting her was pure serendipity.", "Persian: Serendip", "ser-en-DIP-i-tee", 2, "General"},
  {"Pragmatic", "Dealing with things in a practical way", "Take a pragmatic approach to problem-solving.", "Greek: pragmatikos", "prag-MAT-ik", 2, "General"},
  {"Mellifluous", "Sweet or musical sounding", "Her mellifluous voice enchanted the audience.", "Latin: mel + fluere", "muh-LIF-loo-us", 3, "General"},
  {"Obfuscate", "To make something unclear", "Don't obfuscate the issue with vague language.", "Latin: obfuscare", "OB-fus-kayt", 3, "General"},
  {"Paradigm", "A typical example or pattern", "This discovery changed the scientific paradigm.", "Greek: paradeigma", "PAIR-uh-dym", 2, "Academic"},
  {"Zenith", "The highest point or peak", "His career reached its zenith at age 40.", "Arabic: samt", "ZEE-nith", 1, "General"},
  {"Nostalgic", "Sentimental about the past", "The old song made her feel nostalgic.", "Greek: nostos + algos", "nos-TAL-jik", 1, "General"},
  {"Resilient", "Able to recover quickly", "The community proved resilient after the disaster.", "Latin: resilire", "ruh-ZIL-yunt", 2, "General"},
  {"Meticulous", "Very careful and precise", "She is meticulous in her attention to detail.", "Latin: meticulosus", "muh-TIK-yuh-lus", 2, "General"},
  {"Ambiguous", "Open to more than one meaning", "His statement was ambiguous and confusing.", "Latin: ambiguus", "am-BIG-yuh-us", 2, "General"},
  {"Petulant", "Childishly sulky or bad-tempered", "The child's petulant behavior annoyed everyone.", "Latin: petulans", "PET-yuh-lunt", 2, "General"},
  {"Eloquence", "Fluent and persuasive speech", "The eloquence of her argument won the debate.", "Latin: eloquens", "EL-uh-kwents", 2, "General"},
  {"Fastidious", "Very particular about details", "He is fastidious about cleanliness.", "Latin: fastidiosus", "fa-STID-ee-us", 2, "General"},
  {"Gregarious", "Fond of being in crowds", "Humans are naturally gregarious creatures.", "Latin: gregarius", "gruh-GAIR-ee-us", 2, "General"},
  {"Hiatus", "A pause or gap in continuity", "The company took a hiatus from production.", "Latin: hiatus", "hy-AY-tus", 2, "General"},
  {"Incisive", "Intelligently keen and analytical", "The critic's incisive review was spot-on.", "Latin: incidere", "in-SY-siv", 2, "General"},
  {"Jubilant", "Joyful and triumphant", "The crowd was jubilant after winning the game.", "Latin: jubilans", "JOO-buh-lunt", 1, "General"},
  {"Candid", "Truthful and direct", "She gave a candid answer to the question.", "Latin: candidus", "KAN-did", 1, "General"},
  {"Frugal", "Careful with money or resources", "His frugal habits helped him save early.", "Latin: frugalis", "FROO-gul", 1, "General"},
  {"Diligent", "Showing steady, careful effort", "A diligent student reviews notes daily.", "Latin: diligere", "DIL-i-jent", 1, "General"},
  {"Vivid", "Producing strong, clear images", "She gave a vivid account of the trip.", "Latin: vividus", "VIV-id", 1, "General"},
  {"Subtle", "Delicate and hard to notice", "There was a subtle change in his tone.", "Latin: subtilis", "SUT-ul", 1, "General"},
  {"Keen", "Sharp, eager, or intense", "She has a keen eye for design.", "Old English: cene", "KEEN", 1, "General"},
  {"Adverse", "Harmful or unfavorable", "The drug has no adverse effects.", "Latin: adversus", "AD-vurs", 1, "General"},
  {"Abundant", "Existing in large quantities", "The valley has abundant rainfall.", "Latin: abundare", "uh-BUN-dunt", 1, "Nature"},
  {"Brisk", "Quick, active, and energetic", "They kept a brisk pace on the walk.", "French: brusque", "BRISK", 1, "General"},
  {"Dismal", "Gloomy and depressing", "The team gave a dismal performance.", "Latin: dies mali", "DIZ-mul", 1, "General"},
  {"Eager", "Full of keen desire", "He was eager to start the new job.", "Latin: acer", "EE-gur", 1, "Emotions"},
  {"Feeble", "Lacking strength", "She heard a feeble cry for help.", "Latin: flebilis", "FEE-bul", 1, "General"},
  {"Genuine", "Real; truly what it seems", "He showed genuine concern for others.", "Latin: genuinus", "JEN-yoo-in", 1, "General"},
  {"Hasty", "Done with too much speed", "A hasty decision often brings regret.", "French: haste", "HAY-stee", 1, "General"},
  {"Idle", "Not active or in use", "The machines sat idle all week.", "Old English: idel", "EYE-dul", 1, "General"},
  {"Jovial", "Cheerful and friendly", "Our jovial host kept everyone laughing.", "Latin: Jovialis", "JOH-vee-ul", 1, "Emotions"},
  {"Lucid", "Clear and easy to understand", "She gave a lucid explanation of the plan.", "Latin: lucidus", "LOO-sid", 1, "Academic"},
  {"Mimic", "To imitate closely", "Parrots can mimic human speech.", "Greek: mimos", "MIM-ik", 1, "General"},
  {"Novel", "New and original", "They proposed a novel solution.", "Latin: novus", "NOV-ul", 1, "Academic"},
  {"Placid", "Calm and peaceful", "The lake was placid at dawn.", "Latin: placidus", "PLAS-id", 1, "Nature"},
  {"Robust", "Strong and healthy; sturdy", "The bridge has a robust design.", "Latin: robustus", "roh-BUST", 1, "General"},
  {"Sturdy", "Strongly built", "He bought a sturdy pair of boots.", "Old French: estourdi", "STUR-dee", 1, "General"},
  {"Tedious", "Boring and too long", "Filing reports is tedious work.", "Latin: taedium", "TEE-dee-us", 1, "General"},
  {"Vague", "Unclear or imprecise", "His directions were too vague to follow.", "Latin: vagus", "VAYG", 1, "General"},
  {"Wary", "Cautious about danger", "Be wary of offers that sound too good.", "Old English: waer", "WAIR-ee", 1, "General"},
  {"Zeal", "Great energy and enthusiasm", "She pursued the project with zeal.", "Greek: zelos", "ZEEL", 1, "Emotions"},
  {"Ample", "More than enough", "There is ample time to prepare.", "Latin: amplus", "AM-pul", 1, "General"},
  {"Bleak", "Cold, bare, or without hope", "The forecast for the harvest was bleak.", "Old Norse: bleikr", "BLEEK", 1, "General"},
  {"Concise", "Brief but complete", "Keep the summary concise.", "Latin: concidere", "kun-SYS", 1, "Academic"},
  {"Drowsy", "Sleepy and sluggish", "The warm room made her drowsy.", "Old English: drusian", "DROW-zee", 1, "General"},
  {"Earnest", "Serious and sincere", "He made an earnest promise to help.", "Old English: eornoste", "UR-nist", 1, "Emotions"},
  {"Flimsy", "Weak and poorly made", "The shed was too flimsy for the storm.", "Origin uncertain", "FLIM-zee", 1, "General"},
  {"Grim", "Very serious or gloomy", "The rescuers faced a grim task.", "Old English: grimm", "GRIM", 1, "General"},
  {"Humble", "Modest; not proud", "She stayed humble despite her fame.", "Latin: humilis", "HUM-bul", 1, "General"},
  {"Immense", "Extremely large", "The project required immense effort.", "Latin: immensus", "ih-MENS", 1, "General"},
  {"Prudent", "Acting with care and thought", "It is prudent to save for emergencies.", "Latin: prudens", "PROO-dent", 1, "Business"},
  {"Reckless", "Without thinking of consequences", "Reckless driving causes accidents.", "Old English: receleas", "REK-lis", 1, "General"},
  {"Somber", "Dark, gloomy, or serious", "The funeral had a somber mood.", "Latin: sub + umbra", "SOM-bur", 1, "Emotions"},
  {"Thrive", "To grow and do well", "Small businesses thrive in this town.", "Old Norse: thrifask", "THRYV", 1, "Business"},
  {"Weary", "Very tired", "The travelers were weary after the ride.", "Old English: werig", "WEER-ee", 1, "General"},
  {"Empathy", "Understanding another's feelings", "Nurses show empathy every day.", "Greek: empatheia", "EM-puh-thee", 1, "Emotions"},
  {"Tranquil", "Free from disturbance; calm", "The garden was tranquil at sunrise.", "Latin: tranquillus", "TRANG-kwil", 1, "Nature"},
  {"Astute", "Clever and quick at judging", "An astute investor spotted the trend early.", "Latin: astutus", "uh-STOOT", 2, "Business"},
  {"Benevolent", "Kind and generous", "A benevolent donor funded the library.", "Latin: bene + velle", "buh-NEV-uh-lunt", 2, "General"},
  {"Coherent", "Logical and consistent", "Her essay presents a coherent argument.", "Latin: cohaerere", "koh-HEER-unt", 2, "Academic"},
  {"Debilitate", "To weaken severely", "The illness debilitated him for weeks.", "Latin: debilis", "dih-BIL-i-tayt", 2, "Science"},
  {"Empirical", "Based on observation or experiment", "The theory lacks empirical support.", "Greek: empeiria", "em-PIR-i-kul", 2, "Science"},
  {"Feasible", "Possible to do easily", "The plan is feasible within our budget.", "French: faisable", "FEE-zuh-bul", 2, "Business"},
  {"Galvanize", "To shock into action", "The speech galvanized the volunteers.", "After L. Galvani", "GAL-vuh-nyz", 2, "General"},
  {"Hypothesis", "A testable proposed explanation", "The data supported her hypothesis.", "Greek: hypotithenai", "hy-POTH-uh-sis", 2, "Science"},
  {"Impartial", "Treating all sides equally", "Judges must remain impartial.", "Latin: in + pars", "im-PAR-shul", 2, "Law"},
  {"Jeopardize", "To put at risk", "Don't jeopardize your health for work.", "French: jeu parti", "JEP-ur-dyz", 2, "General"},
  {"Lament", "To express deep sorrow", "Fans lamented the singer's retirement.", "Latin: lamentari", "luh-MENT", 2, "Emotions"},
  {"Meander", "To wander without direction", "The river meanders through the valley.", "Greek: Maiandros", "mee-AN-dur", 2, "Nature"},
  {"Nonchalant", "Calmly unconcerned", "He was nonchalant about the deadline.", "French: nonchaloir", "non-shuh-LAHNT", 2, "Emotions"},
  {"Optimize", "To make as effective as possible", "We optimized the code for speed.", "Latin: optimus", "OP-tuh-myz", 2, "Business"},
  {"Plausible", "Seemingly reasonable or likely", "She offered a plausible excuse.", "Latin: plausibilis", "PLAW-zuh-bul", 2, "Academic"},
  {"Quaint", "Attractively old-fashioned", "They stayed in a quaint village inn.", "Latin: cognitus", "KWAYNT", 2, "General"},
  {"Rigorous", "Extremely thorough and strict", "The study used rigorous methods.", "Latin: rigor", "RIG-ur-us", 2, "Academic"},
  {"Skeptical", "Doubting; not easily convinced", "Scientists were skeptical of the claim.", "Greek: skeptikos", "SKEP-ti-kul", 2, "Science"},
  {"Tenacious", "Holding firmly; persistent", "Her tenacious spirit carried the team.", "Latin: tenax", "tuh-NAY-shus", 2, "General"},
  {"Unprecedented", "Never done or known before", "The storm caused unprecedented damage.", "Latin: prae + cedere", "un-PRES-i-den-tid", 2, "General"},
  {"Versatile", "Adaptable to many uses", "A versatile tool for every job.", "Latin: versare", "VUR-suh-tul", 2, "General"},
  {"Wistful", "Full of gentle longing", "She gave a wistful look at the old house.", "English: wistly", "WIST-ful", 2, "Emotions"},
  {"Alleviate", "To make less severe", "The medicine alleviated her pain.", "Latin: levis", "uh-LEE-vee-ayt", 2, "Science"},
  {"Advocate", "To publicly support", "She advocates for cleaner energy.", "Latin: advocare", "AD-vuh-kayt", 2, "Law"},
  {"Arbitrary", "Based on whim, not reason", "The rule seemed entirely arbitrary.", "Latin: arbiter", "AR-bi-trair-ee", 2, "Law"},
  {"Articulate", "Expressing ideas clearly", "He is remarkably articulate under pressure.", "Latin: articulare", "ar-TIK-yuh-lit", 2, "General"},
  {"Augment", "To make greater; increase", "She augments her income with tutoring.", "Latin: augere", "awg-MENT", 2, "Business"},
  {"Belligerent", "Hostile and aggressive", "The belligerent customer demanded a refund.", "Latin: bellum gerere", "buh-LIJ-ur-unt", 2, "Emotions"},
  {"Compelling", "Powerfully convincing", "The lawyer made a compelling case.", "Latin: compellere", "kum-PEL-ing", 2, "Law"},
  {"Condone", "To accept or overlook wrongdoing", "The school does not condone cheating.", "Latin: condonare", "kun-DOHN", 2, "Law"},
  {"Copious", "Abundant in quantity", "He took copious notes in class.", "Latin: copia", "KOH-pee-us", 2, "Academic"},
  {"Cryptic", "Mysterious; hard to interpret", "She left a cryptic note on the desk.", "Greek: kryptos", "KRIP-tik", 2, "General"},
  {"Deference", "Respectful submission to another", "He bowed in deference to the judge.", "Latin: deferre", "DEF-ur-uns", 2, "General"},
  {"Diminish", "To make or become smaller", "Nothing can diminish her achievement.", "Latin: minuere", "dih-MIN-ish", 2, "General"},
  {"Eclectic", "Drawn from diverse sources", "The cafe plays an eclectic mix of music.", "Greek: eklegein", "ih-KLEK-tik", 2, "Arts"},
  {"Elusive", "Hard to find or catch", "Success remained elusive for years.", "Latin: eludere", "ih-LOO-siv", 2, "General"},
  {"Endorse", "To publicly approve", "The union endorsed the candidate.", "Latin: in + dorsum", "en-DORS", 2, "Business"},
  {"Exemplary", "Serving as an ideal model", "Her conduct was exemplary.", "Latin: exemplum", "ig-ZEM-pluh-ree", 2, "General"},
  {"Flourish", "To grow vigorously; thrive", "The arts flourished in that era.", "Latin: florere", "FLUR-ish", 2, "Arts"},
  {"Formidable", "Inspiring fear or respect", "They faced a formidable opponent.", "Latin: formidare", "FOR-mi-duh-bul", 2, "General"},
  {"Futile", "Producing no useful result", "Resistance proved futile.", "Latin: futilis", "FYOO-tul", 2, "General"},
  {"Hostile", "Unfriendly; antagonistic", "The proposal met a hostile reception.", "Latin: hostis", "HOS-tul", 2, "Emotions"},
  {"Immutable", "Unchangeable over time", "The laws of physics are immutable.", "Latin: mutare", "ih-MYOO-tuh-bul", 2, "Science"},
  {"Indifferent", "Having no interest or concern", "He seemed indifferent to the outcome.", "Latin: indifferens", "in-DIF-ur-unt", 2, "Emotions"},
  {"Innovate", "To introduce new methods", "Startups must innovate to survive.", "Latin: novare", "IN-uh-vayt", 2, "Business"},
  {"Intricate", "Very detailed and complex", "The watch has an intricate mechanism.", "Latin: intricare", "IN-tri-kit", 2, "General"},
  {"Lethargic", "Sluggish and without energy", "The heat made everyone lethargic.", "Greek: lethargos", "luh-THAR-jik", 2, "Science"},
  {"Lucrative", "Producing much profit", "Consulting became a lucrative career.", "Latin: lucrum", "LOO-kruh-tiv", 2, "Business"},
  {"Mediate", "To help settle a dispute", "A neutral party mediated the talks.", "Latin: mediare", "MEE-dee-ayt", 2, "Law"},
  {"Mundane", "Ordinary and dull", "He escaped his mundane routine.", "Latin: mundus", "mun-DAYN", 2, "General"},
  {"Notorious", "Famous for something bad", "The pass is notorious for sudden storms.", "Latin: notus", "noh-TOR-ee-us", 2, "General"},
  {"Objective", "Not influenced by feelings", "Reporters should stay objective.", "Latin: obiectum", "ub-JEK-tiv", 2, "Academic"},
  {"Ominous", "Suggesting something bad will happen", "Ominous clouds gathered over the bay.", "Latin: omen", "OM-i-nus", 2, "Nature"},
  {"Pinnacle", "The most successful point", "The award marked the pinnacle of her career.", "Latin: pinnaculum", "PIN-uh-kul", 2, "General"},
  {"Profound", "Very deep or intense", "The book had a profound effect on me.", "Latin: profundus", "pruh-FOWND", 2, "Academic"},
  {"Prolific", "Producing much work or fruit", "He was a prolific writer of essays.", "Latin: proles", "pruh-LIF-ik", 2, "Arts"},
  {"Redundant", "No longer needed; repetitive", "Remove the redundant sentences.", "Latin: redundare", "rih-DUN-dunt", 2, "Academic"},
  {"Reluctant", "Unwilling and hesitant", "She was reluctant to leave early.", "Latin: reluctari", "rih-LUK-tunt", 2, "Emotions"},
  {"Scrutinize", "To examine very closely", "Auditors scrutinized the accounts.", "Latin: scrutari", "SKROO-tuh-nyz", 2, "Law"},
  {"Static", "Not moving or changing", "Sales stayed static all quarter.", "Greek: statikos", "STAT-ik", 2, "Science"},
  {"Subordinate", "Lower in rank or importance", "He treats subordinate staff with respect.", "Latin: sub + ordinare", "suh-BOR-di-nit", 2, "Business"},
  {"Substantiate", "To provide evidence for", "Can you substantiate that claim?", "Latin: substantia", "sub-STAN-shee-ayt", 2, "Law"},
  {"Tangible", "Real; able to be touched", "The training brought tangible results.", "Latin: tangere", "TAN-juh-bul", 2, "Business"},
  {"Transient", "Lasting only a short time", "City centers have transient populations.", "Latin: transire", "TRAN-zee-unt", 2, "Academic"},
  {"Turbulent", "Full of disorder or confusion", "They lived through turbulent times.", "Latin: turba", "TUR-byuh-lunt", 2, "General"},
  {"Vigilant", "Watchful for danger", "Stay vigilant against online scams.", "Latin: vigilare", "VIJ-uh-lunt", 2, "General"},
  {"Volatile", "Changing rapidly; unstable", "Oil prices are volatile this year.", "Latin: volare", "VOL-uh-tul", 2, "Business"},
  {"Zealot", "A fanatic for a cause", "He argued like a zealot, not a scholar.", "Greek: zelotes", "ZEL-ut", 2, "General"},
  {"Abate", "To lessen in intensity", "The storm finally abated at dawn.", "French: abattre", "uh-BAYT", 2, "Nature"},
  {"Adept", "Highly skilled", "She is adept at solving disputes.", "Latin: adipisci", "uh-DEPT", 2, "General"},
  {"Affluent", "Wealthy; prosperous", "They moved to an affluent suburb.", "Latin: affluere", "AF-loo-unt", 2, "Business"},
  {"Coerce", "To force by threats", "He was coerced into signing.", "Latin: coercere", "koh-URS", 2, "Law"},
  {"Collaborate", "To work jointly with others", "The labs collaborate on research.", "Latin: com + laborare", "kuh-LAB-uh-rayt", 2, "Business"},
  {"Complacent", "Smugly self-satisfied", "Success made the team complacent.", "Latin: complacere", "kum-PLAY-sunt", 2, "Emotions"},
  {"Comprehensive", "Including all or nearly all", "The report gives a comprehensive overview.", "Latin: comprehendere", "kom-pri-HEN-siv", 2, "Academic"},
  {"Deteriorate", "To become progressively worse", "The building deteriorated for decades.", "Latin: deterior", "dih-TEER-ee-uh-rayt", 2, "General"},
  {"Divert", "To change the direction of", "Traffic was diverted around the crash.", "Latin: divertere", "dih-VURT", 2, "General"},
  {"Emulate", "To imitate in order to match", "Young players emulate their heroes.", "Latin: aemulari", "EM-yuh-layt", 2, "General"},
  {"Enigma", "A puzzling mystery", "The ruins remain an enigma to scholars.", "Greek: ainigma", "ih-NIG-muh", 2, "General"},
  {"Fluctuate", "To rise and fall irregularly", "Demand fluctuates with the seasons.", "Latin: fluctus", "FLUK-choo-ayt", 2, "Business"},
  {"Hindrance", "Something that blocks progress", "Red tape is a hindrance to growth.", "Old English: hindrian", "HIN-druns", 2, "Business"},
  {"Inevitable", "Certain to happen", "Change is inevitable in technology.", "Latin: evitare", "in-EV-i-tuh-bul", 2, "General"},
  {"Integrity", "Honesty and strong morals", "She acted with complete integrity.", "Latin: integer", "in-TEG-ri-tee", 2, "General"},
  {"Legacy", "Something handed down", "The park is her lasting legacy.", "Latin: legare", "LEG-uh-see", 2, "General"},
  {"Mitigate", "To make less severe", "Levees mitigate flood damage.", "Latin: mitis", "MIT-i-gayt", 2, "Science"},
  {"Persevere", "To keep trying despite difficulty", "She persevered through every setback.", "Latin: perseverus", "pur-suh-VEER", 2, "Emotions"},
  {"Preliminary", "Coming before the main part", "Preliminary results look promising.", "Latin: prae + limen", "prih-LIM-uh-nair-ee", 2, "Academic"},
  {"Speculate", "To guess without full evidence", "Analysts speculate about a merger.", "Latin: speculari", "SPEK-yuh-layt", 2, "Business"},
  {"Viable", "Capable of working or surviving", "Solar power is now a viable option.", "Latin: vita", "VY-uh-bul", 2, "Science"},
  {"Anomaly", "Something that deviates from normal", "The sensor flagged an anomaly in the data.", "Greek: anomalos", "uh-NOM-uh-lee", 2, "Science"},
  {"Benchmark", "A standard for comparison", "The results set a new benchmark.", "English: bench + mark", "BENCH-mark", 2, "Business"},
  {"Catalyst", "Something that triggers change", "The film was a catalyst for reform.", "Greek: katalysis", "KAT-uh-list", 2, "Science"},
  {"Consensus", "General agreement", "The committee reached a consensus.", "Latin: consentire", "kun-SEN-sus", 2, "Business"},
  {"Credible", "Able to be believed", "The witness gave a credible account.", "Latin: credere", "KRED-uh-bul", 2, "Law"},
  {"Dormant", "Inactive but able to awaken", "The volcano has been dormant for centuries.", "Latin: dormire", "DOR-munt", 2, "Nature"},
  {"Emphatic", "Expressed with force", "She gave an emphatic denial.", "Greek: emphainein", "em-FAT-ik", 2, "General"},
  {"Kinetic", "Relating to motion", "The sculpture uses kinetic energy.", "Greek: kinein", "ki-NET-ik", 2, "Science"},
  {"Luminous", "Giving off light; glowing", "Luminous jellyfish drifted below.", "Latin: lumen", "LOO-muh-nus", 2, "Nature"},
  {"Nuance", "A subtle difference in meaning", "Translators must capture every nuance.", "French: nuer", "NOO-ahns", 2, "Arts"},
  {"Pristine", "In its original, pure condition", "The trail leads to a pristine lake.", "Latin: pristinus", "PRIS-teen", 2, "Nature"},
  {"Verbose", "Using more words than needed", "The manual is verbose and confusing.", "Latin: verbum", "vur-BOHS", 2, "Academic"},
  {"Whimsical", "Playfully fanciful", "The shop sells whimsical toys.", "English: whimsy", "WIM-zi-kul", 2, "Arts"},
  {"Brevity", "Shortness of expression", "Brevity is the soul of wit.", "Latin: brevis", "BREV-i-tee", 2, "Academic"},
  {"Culminate", "To reach a final high point", "Months of work culminated in the launch.", "Latin: culmen", "KUL-muh-nayt", 2, "General"},
  {"Dexterity", "Skill with the hands or mind", "Surgeons need great dexterity.", "Latin: dexter", "dek-STAIR-i-tee", 2, "Science"},
  {"Frivolous", "Not serious; trivial", "The court dismissed the frivolous suit.", "Latin: frivolus", "FRIV-uh-lus", 2, "Law"},
  {"Pensive", "Deeply or dreamily thoughtful", "He grew pensive at the mention of home.", "Latin: pensare", "PEN-siv", 2, "Emotions"},
  {"Stoic", "Enduring pain without complaint", "She remained stoic through the ordeal.", "Greek: stoa", "STOH-ik", 2, "Emotions"},
  {"Aberration", "A departure from what is normal", "The cold summer was an aberration.", "Latin: aberrare", "ab-uh-RAY-shun", 3, "Science"},
  {"Acquiesce", "To accept without protest", "She acquiesced to the new terms.", "Latin: acquiescere", "ak-wee-ES", 3, "General"},
  {"Alacrity", "Cheerful eagerness", "He accepted the offer with alacrity.", "Latin: alacer", "uh-LAK-ri-tee", 3, "Emotions"},
  {"Anachronism", "Something out of its proper time", "A sword is an anachronism in modern war.", "Greek: ana + chronos", "uh-NAK-ruh-niz-um", 3, "Academic"},
  {"Antithesis", "The direct opposite", "His calm was the antithesis of her fury.", "Greek: antitithenai", "an-TITH-uh-sis", 3, "Academic"},
  {"Apocryphal", "Of doubtful authenticity", "The quote is probably apocryphal.", "Greek: apokryphos", "uh-POK-ruh-ful", 3, "Academic"},
  {"Ascetic", "Practicing severe self-discipline", "The monk led an ascetic life.", "Greek: asketes", "uh-SET-ik", 3, "General"},
  {"Cacophony", "A harsh mix of sounds", "A cacophony of horns filled the street.", "Greek: kakos + phone", "kuh-KOF-uh-nee", 3, "Arts"},
  {"Capitulate", "To surrender; give in", "The board capitulated to the investors.", "Latin: capitulare", "kuh-PICH-uh-layt", 3, "Business"},
  {"Catharsis", "Emotional release and relief", "Writing the letter brought catharsis.", "Greek: katharsis", "kuh-THAR-sis", 3, "Emotions"},
  {"Circumspect", "Careful; considering all risks", "Be circumspect when signing contracts.", "Latin: circumspicere", "SUR-kum-spekt", 3, "Law"},
  {"Conflate", "To merge distinct things into one", "Don't conflate price with value.", "Latin: conflare", "kun-FLAYT", 3, "Academic"},
  {"Deleterious", "Causing harm or damage", "Smoking has deleterious effects.", "Greek: deleterios", "del-i-TEER-ee-us", 3, "Science"},
  {"Demagogue", "A leader who exploits prejudice", "The demagogue stirred the crowd's fears.", "Greek: demos + agogos", "DEM-uh-gog", 3, "General"},
  {"Didactic", "Intended to teach, often preachy", "The novel felt too didactic.", "Greek: didaskein", "dy-DAK-tik", 3, "Academic"},
  {"Dilettante", "A dabbler without real commitment", "He paints as a dilettante, not a pro.", "Italian: dilettare", "DIL-i-tahnt", 3, "Arts"},
  {"Ebullient", "Overflowing with enthusiasm", "Her ebullient mood lifted the room.", "Latin: ebullire", "ih-BUL-yunt", 3, "Emotions"},
  {"Egregious", "Outstandingly bad", "That was an egregious error.", "Latin: ex + grex", "ih-GREE-jus", 3, "General"},
  {"Equanimity", "Calmness under stress", "She faced the crisis with equanimity.", "Latin: aequus + animus", "ek-wuh-NIM-i-tee", 3, "Emotions"},
  {"Esoteric", "Understood by few; obscure", "The lecture was too esoteric for most.", "Greek: esoterikos", "es-uh-TAIR-ik", 3, "Academic"},
  {"Exacerbate", "To make a problem worse", "Delays exacerbated the shortage.", "Latin: acerbus", "ig-ZAS-ur-bayt", 3, "General"},
  {"Fatuous", "Silly and pointless", "He made a fatuous remark in the meeting.", "Latin: fatuus", "FACH-oo-us", 3, "General"},
  {"Garrulous", "Excessively talkative", "A garrulous guide dominated the tour.", "Latin: garrire", "GAIR-uh-lus", 3, "General"},
  {"Hegemony", "Dominance of one group", "The empire held hegemony over trade.", "Greek: hegemon", "hih-JEM-uh-nee", 3, "Academic"},
  {"Iconoclast", "One who attacks cherished beliefs", "The critic was a famous iconoclast.", "Greek: eikon + klan", "eye-KON-uh-klast", 3, "Arts"},
  {"Idiosyncrasy", "A peculiar personal habit", "Humming while coding is his idiosyncrasy.", "Greek: idios + syn", "id-ee-oh-SIN-kruh-see", 3, "General"},
  {"Impecunious", "Having little or no money", "An impecunious student rents a tiny room.", "Latin: pecunia", "im-pi-KYOO-nee-us", 3, "Business"},
  {"Inexorable", "Impossible to stop", "The inexorable rise of automation.", "Latin: exorare", "in-EK-sur-uh-bul", 3, "General"},
  {"Insidious", "Harmful in a gradual, subtle way", "Rust is an insidious enemy of bridges.", "Latin: insidiae", "in-SID-ee-us", 3, "Science"},
  {"Intransigent", "Refusing to compromise", "Talks stalled with both sides intransigent.", "Latin: transigere", "in-TRAN-si-junt", 3, "Law"},
  {"Laconic", "Using very few words", "His laconic reply ended the debate.", "Greek: Lakonikos", "luh-KON-ik", 3, "General"},
  {"Magnanimous", "Generous toward a rival", "She was magnanimous in victory.", "Latin: magnus + animus", "mag-NAN-uh-mus", 3, "Emotions"},
  {"Myriad", "A countless great number", "The reef hosts a myriad of species.", "Greek: myrias", "MEER-ee-ud", 3, "Nature"},
  {"Nefarious", "Wicked or criminal", "They exposed a nefarious scheme.", "Latin: nefas", "nih-FAIR-ee-us", 3, "Law"},
  {"Obsequious", "Excessively eager to please", "The obsequious clerk flattered every client.", "Latin: obsequi", "ub-SEE-kwee-us", 3, "General"},
  {"Ostensible", "Stated but not necessarily true", "The ostensible reason was cost.", "Latin: ostendere", "os-TEN-suh-bul", 3, "Law"},
  {"Panacea", "A cure-all solution", "Technology is no panacea for poverty.", "Greek: panakeia", "pan-uh-SEE-uh", 3, "Science"},
  {"Paradox", "A self-contradictory truth", "It's a paradox that less can be more.", "Greek: paradoxos", "PAIR-uh-doks", 3, "Academic"},
  {"Pejorative", "Expressing disapproval", "Avoid pejorative labels in reports.", "Latin: peior", "pih-JOR-uh-tiv", 3, "Academic"},
  {"Perfunctory", "Done without real care", "He gave the report a perfunctory glance.", "Latin: perfungi", "pur-FUNK-tuh-ree", 3, "General"},
  {"Pernicious", "Very harmful, often subtly", "Rumors have a pernicious effect on trust.", "Latin: pernicies", "pur-NISH-us", 3, "General"},
  {"Perspicacious", "Having sharp insight", "A perspicacious editor caught the flaw.", "Latin: perspicax", "pur-spi-KAY-shus", 3, "Academic"},
  {"Pithy", "Brief and full of meaning", "She summed it up in one pithy line.", "Old English: pitha", "PITH-ee", 3, "Arts"},
  {"Precarious", "Dangerously insecure", "The ladder stood at a precarious angle.", "Latin: precarius", "prih-KAIR-ee-us", 3, "General"},
  {"Proclivity", "A natural tendency", "He has a proclivity for risk-taking.", "Latin: proclivis", "proh-KLIV-i-tee", 3, "General"},
  {"Quintessential", "The most perfect example", "The quintessential summer meal.", "Latin: quinta essentia", "kwin-tuh-SEN-shul", 3, "General"},
  {"Recalcitrant", "Stubbornly uncooperative", "A recalcitrant witness delayed the trial.", "Latin: recalcitrare", "rih-KAL-si-trunt", 3, "Law"},
  {"Sagacious", "Wise and shrewd in judgment", "A sagacious mentor guided her career.", "Latin: sagax", "suh-GAY-shus", 3, "General"},
  {"Sanguine", "Optimistic despite difficulty", "He stayed sanguine about the launch.", "Latin: sanguis", "SANG-gwin", 3, "Emotions"},
  {"Soporific", "Causing sleepiness", "The lecture had a soporific effect.", "Latin: sopor", "sop-uh-RIF-ik", 3, "Science"},
  {"Spurious", "False though seeming genuine", "The paper relied on spurious data.", "Latin: spurius", "SPYUR-ee-us", 3, "Science"},
  {"Sycophant", "A servile flatterer", "Leaders surrounded by sycophants fail.", "Greek: sykophantes", "SIK-uh-funt", 3, "General"},
  {"Taciturn", "Habitually silent", "The taciturn farmer rarely spoke.", "Latin: tacere", "TAS-i-turn", 3, "General"},
  {"Trepidation", "Fear about what may happen", "She opened the results with trepidation.", "Latin: trepidare", "trep-i-DAY-shun", 3, "Emotions"},
  {"Truculent", "Quick to argue or fight", "The truculent driver refused to move.", "Latin: trux", "TRUK-yuh-lunt", 3, "General"},
  {"Vicissitude", "An unwelcome change of fortune", "They endured the vicissitudes of war.", "Latin: vicis", "vi-SIS-i-tood", 3, "General"},
  {"Vituperate", "To criticize harshly", "Critics vituperated the sequel.", "Latin: vitium", "vy-TOO-puh-rayt", 3, "General"},
  {"Derivative", "Copied from something else", "The plot felt derivative of older films.", "Latin: derivare", "dih-RIV-uh-tiv", 3, "Arts"},
  {"Iridescent", "Showing shifting rainbow colors", "The beetle's shell was iridescent.", "Latin: iris", "ir-i-DES-unt", 3, "Nature"},
  {"Juxtapose", "To place side by side to compare", "The exhibit juxtaposes old and new art.", "Latin: iuxta + poser", "JUK-stuh-pohz", 3, "Arts"},
  {"Symbiosis", "Mutually beneficial relationship", "Fungi and trees live in symbiosis.", "Greek: symbioun", "sim-bee-OH-sis", 3, "Nature"},
  {"Austere", "Severely plain; strict", "The room was austere but elegant.", "Greek: austeros", "aw-STEER", 3, "Arts"},
  {"Gratuitous", "Uncalled for; unnecessary", "The critics panned its gratuitous scenes.", "Latin: gratuitus", "gruh-TOO-i-tus", 3, "Arts"},
  {"Meritocracy", "Advancement based on ability", "The firm claims to be a meritocracy.", "Latin: meritum", "mair-i-TOK-ruh-see", 3, "Business"},
};

#define VOCAB_COUNT (sizeof(vocab_list) / sizeof(vocab_list[0]))

#endif
